[tool.poetry]
name = "aws-chalice-cii-cd"
version = "0.1.0"
description = ""
authors = ["erick <martinoli944@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
chalice = "^1.31.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
