name: CI Pipeline

on:
  push:
    branches: ['main', 'development']

jobs:
  setup-credentials:
    runs-on: ubuntu-latest
    outputs:
      AWS_REGION:  ${{ steps.condition.outputs.aws_region }}
      STAGE:  ${{ steps.condition.outputs.stage }}
    steps:
      - uses: actions/checkout@v2
      - name: Set variables
        id: condition
        run: |
          if [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
            echo "Prod branch!"
            echo "aws_region=us-east-1" >> "$GITHUB_OUTPUT"
            echo "stage=prod" >> "$GITHUB_OUTPUT"
          else
            echo "Dev branch!"
            echo "aws_region=us-east-1" >> "$GITHUB_OUTPUT"
            echo "stage=dev" >> "$GITHUB_OUTPUT"
          fi
        shell: bash
      - name: Check variables
        run: |
          echo "Region: ${{ steps.condition.outputs.aws_region }} Stage: ${{ steps.condition.outputs.stage }}"
  build:
    env:
        STAGE:   ${{needs.setup-credentials.outputs.STAGE}}
    runs-on: ubuntu-latest
    needs: setup-credentials
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: chalice deploy
        uses: jayef0/chalice-extended-action@release-v0.2.1
        env:
          WORKING_DIRECTORY: ./
          REQUIREMENTS_FILE: requirements.txt
          OPERATION: deploy
          STAGE: ${{env.STAGE}}
          AWS_ACCESS_KEY_ID:  ${{secrets.AWS_ACCESS_KEY_ID_DEV}}
          AWS_SECRET_ACCESS_KEY:  ${{secrets.AWS_SECRET_ACCESS_KEY_DEV}}
          AWS_DEFAULT_REGION:  ${{needs.setup-credentials.outputs.AWS_REGION}}
